### ISSUE TITLE
Request a new service - Service already exists does not display service

### ISSUE THREAD

**Issue by abekfenn** [tosdr/CrispCMS#139]
## Description
When requested a new service, if the service already exists an error is generated that tells the user that the service has already been evaluated by tos;dr, or exists, without telling the user how to find the report evaluating that service.

### How To Reproduce It
1. _Go to_ [New Service](https://tosdr.org/en/new_service)
2. _Click in 'Service Name' text box_ 
3. Type in "Shift"
4. _Click in 'Service Domains' text box_ 
5. Type in "tryshift.com"
6. _Click in 'Documents' text section_ 
7. Add "Privacy Policy" document from [Privacy Policy](https://tryshift.com/privacy/)
8. Add "Terms of Use" document from [Terms of Use](https://tryshift.com/terms/)
9. Add "End User License Agreement" document from [End User License Agreement](https://tryshift.com/eula/)
10. _XPath of "/html/body/div/div[3]" can be used for all of the above documents_ ☝️ 
11. _Scroll down to 'Submit' and click Submit button_
12. _See error_
> An error occurred submitting the service: Service Request already exists
13. Navigate to [Ratings](https://tosdr.org/en/frontpage#ratings)
14. Type in Shift
15. See no relevant results for tryshift.com

### Expected behavior
The user receives a message that tells them how to find the report for the already evaluated service.

### Screenshots
![image](https://user-images.githubusercontent.com/74624810/169731344-58ed56de-311d-4dcd-9c78-9c29a5dfd3a2.png)
![image](https://user-images.githubusercontent.com/74624810/169731714-82609593-d370-4e6e-89c0-a1d62e6427dc.png)

### Response Headers
N/A

## Desktop Specs
 - Mac OS Big Sur 11.2.3
 - Browser  Safari_
 - Browser Version 14.0.3 (16610.4.3.1.7)

## Additional Context
Note: I realize this may be a feature request as opposed to a bug but it feels strange that I get an error and then if I try to search for this service in tos;dr's services, I cannot find it.
Let me know if response headers are needed.

**Comment by JustinBack** [comment]
Hey,

The error message states that the Service Request already exists. We should make it more clear maybe, but its the request that exists, not the service :-)

Best regards,
Justin Back

Terms of Service; Didn’t Read
IT | Software, Cloud, Network, Database Engineer | System Administrator

www.tosdr.org
The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occuring the future.

**Comment by abekfenn** [comment]
Hi @JustinBack thanks for getting back to me. Understood, would you be able to tell me how I can find the existing service request? It didn't turn up in the search on tosdr.org despite trying to look it up.

**Comment by abekfenn** [comment]
Apologies, I read your comment as intended now and understand that you mean that it's the request that exists, not the service "rating". Guess I'll have to wait for that then, thank you!
